#server:
#  port: 8443
#  ssl:
#    key-store: mykeys.jks
#    key-store-password: password
#    key-password: password
#logging:
#  path: /logs
#  file: BookWork.log
#  level:
#    root: debug

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/readinglist
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
server:
  port: 8081